package no.stormberry.usernamegenerator

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Proves the Kotlin sanitiser and the JavaScript one agree.
 *
 * The web app is the reference implementation: it shipped first, and the usernames
 * people already hold were produced by it. If the port disagrees, the same word list
 * yields different usernames on phone and web, which is precisely the failure the
 * README's "all three produce the same shapes" claim would hide.
 *
 * `sanitise-golden.csv` is generated by `tools/gen-sanitise-golden.js`, which lifts
 * the TRANSLITERATE map out of `script.js` rather than duplicating it, and draws its
 * cases from **every non-ASCII character that actually occurs in the 33 dictionary
 * files**. It therefore grows by itself when a dictionary gains a new character, and
 * cannot quietly fall behind the data. Regenerate it whenever either sanitiser or any
 * dictionary changes.
 *
 * Note NFD alone is not enough. Letters like l-stroke, o-stroke, sharp-s, ae and oe
 * are atomic code points with no combining form, so stripping marks leaves them
 * untouched. That is what the TRANSLITERATE map is for, and the corpus covers each
 * entry in it both alone and in context.
 */
class SanitiseGoldenTest {

    private data class Row(val id: String, val description: String, val input: String, val expected: String)

    private val rows: List<Row> by lazy {
        val text = checkNotNull(javaClass.getResourceAsStream("/sanitise-golden.csv")) {
            "sanitise-golden.csv missing from test resources; run tools/gen-sanitise-golden.js"
        }.bufferedReader().readText()

        val lines = text.trim('\n').lines()
        assertEquals(
            "Corpus header changed; the generator and this reader have diverged",
            "case_id,description,input,expected",
            lines.first(),
        )
        lines.drop(1).map { line ->
            // A plain split is safe only because the generator asserts no description
            // contains a comma. If that assertion is ever removed, this breaks loudly
            // rather than silently mis-parsing, because the field count is checked.
            val f = line.split(",")
            require(f.size == 4) { "Malformed corpus row: $line" }
            Row(f[0], f[1], f[2], f[3])
        }
    }

    @Test
    fun `the corpus is not vacuous`() {
        assertTrue("Corpus is suspiciously small: ${rows.size} rows", rows.size >= 40)
        assertTrue(
            "Corpus must contain non-ASCII inputs or it proves nothing",
            rows.any { r -> r.input.any { it.code > 127 } },
        )
        assertTrue(
            "Corpus must cover the transliterate map, which NFD cannot handle",
            rows.any { it.description.startsWith("transliterate") },
        )
    }

    @Test
    fun `every row matches the JavaScript reference exactly`() {
        val failures = rows.mapNotNull { row ->
            val actual = UsernameEngine.sanitise(row.input)
            if (actual == row.expected) null
            else "${row.id} (${row.description}): ${row.input} -> expected '${row.expected}', got '$actual'"
        }
        assertTrue(
            "${failures.size} of ${rows.size} rows disagree with script.js:\n" +
                failures.take(10).joinToString("\n"),
            failures.isEmpty(),
        )
    }

    /**
     * The README, the Zapstore listing and the F-Droid description all claim the
     * result is "accepted everywhere". That is an ASCII claim, so it gets a test
     * rather than a promise.
     */
    @Test
    fun `sanitised output is always ASCII`() {
        val offenders = rows.map { UsernameEngine.sanitise(it.input) }
            .filter { out -> out.any { it.code > 127 } }
        assertTrue(
            "Sanitised output must be ASCII, these are not: $offenders",
            offenders.isEmpty(),
        )
    }
}
