package no.stormberry.usernamegenerator

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pins the Kotlin strength maths to the web app's, row by row.
 *
 * The corpus is generated by tools/gen-strength-golden.js, which LIFTS the
 * functions out of script.js rather than restating them, so this asserts against
 * the code the web app actually runs and not a second description of it.
 * Regenerate after touching the maths, the dictionaries or the entropy model.
 */
class StrengthGoldenTest {

    private data class Row(
        val case: String,
        /** Null for the synthetic rows, which deliberately bypass the table. */
        val language: Language?,
        val wordType: WordType,
        val slots: Int,
        val sizes: List<Int>,
        val addDigits: Boolean,
        val digitCount: Int,
        val separator: Separator,
        val hmin: Double,
        val h2: Double,
        val bitsText: String,
        val combinations: String,
        val collisionAt: String,
    )

    private val dataDir: File by lazy {
        var dir: File? = File(".").canonicalFile
        while (dir != null) {
            val candidate = File(dir, "data")
            if (File(candidate, "en_nouns.txt").isFile) return@lazy candidate
            dir = dir.parentFile
        }
        error("Could not locate data/ by walking up from ${File(".").canonicalPath}")
    }

    private val model: EntropyModel by lazy {
        EntropyModel.parse(File(dataDir, "entropy-model.tsv").readText())
    }

    private val rows: List<Row> by lazy {
        val text = checkNotNull(javaClass.getResourceAsStream("/strength-golden.tsv")) {
            "strength-golden.tsv missing from test resources; run tools/gen-strength-golden.js"
        }.bufferedReader().readText()
        text.trim('\n').lines().filterNot { it.startsWith("#") }.map { line ->
            val f = line.split('\t')
            check(f.size == 13) { "malformed corpus row (${f.size} fields): $line" }
            Row(
                case = f[0],
                // "-" means the row was generated with NO model, to cover the
                // size-based fallback that only runs when the asset is missing.
                language = Language.entries.firstOrNull { it.code == f[1] },
                wordType = WordType.entries.first { it.key == f[2] },
                slots = f[3].toInt(),
                sizes = if (f[4].isEmpty()) emptyList() else f[4].split(' ').map(String::toInt),
                addDigits = f[5] == "1",
                digitCount = f[6].toInt(),
                separator = when (f[7]) {
                    "mix" -> Separator.MIX
                    "random" -> Separator.RANDOM
                    else -> Separator.HYPHEN
                },
                hmin = f[8].toDouble(),
                h2 = f[9].toDouble(),
                bitsText = f[10],
                combinations = f[11],
                collisionAt = f[12],
            )
        }
    }

    @Test
    fun `every golden row matches`() {
        for (row in rows) {
            val plan = UsernameEngine.categoryPlan(row.slots, row.wordType)
            val got = Strength.describe(
                if (row.language == null) null else model,
                plan, row.language ?: Language.EN, row.wordType, row.sizes,
                row.addDigits, row.digitCount, row.separator)
            val where = "${row.case} lang=${row.language?.code ?: "fallback"} " +
                "digits=${row.addDigits}x${row.digitCount}"
            // Raw bits to 1e-9: the displayed decimal agreeing is not enough, because
            // two implementations can round to the same tenth from genuinely different
            // numbers and hide a divergence until some later change crosses a boundary.
            assertEquals("min-entropy differs at $where", row.hmin, got.hmin, 1e-9)
            assertEquals("collision entropy differs at $where", row.h2, got.h2, 1e-9)
            assertEquals("bitsText differs at $where", row.bitsText, got.bitsText)
            assertEquals("combinations differ at $where", row.combinations, got.combinations)
            assertEquals("collisionAt differs at $where", row.collisionAt, got.collisionAt)
        }
    }

    /**
     * A corpus that quietly stopped covering the interesting branches would still
     * pass every assertion above, which is the failure mode worth guarding.
     */
    @Test
    fun `corpus is not vacuous`() {
        assertTrue("corpus has only ${rows.size} rows", rows.size >= 1500)
        val combos = rows.map { it.combinations }
        for (scale in listOf("thousand", "million", "billion", "trillion", "quadrillion", "quintillion")) {
            assertTrue("no row renders at scale '$scale'", combos.any { it.endsWith(" $scale") })
        }
        assertTrue("no row reaches the 10^n branch", combos.any { "10^" in it })
        assertTrue("no row falls below 1000", combos.any { it.all(Char::isDigit) })
        assertTrue("no row covers the no-model fallback", rows.any { it.language == null })
        for (mode in listOf(Separator.RANDOM, Separator.MIX)) {
            assertTrue("no row uses $mode", rows.any { it.separator == mode })
        }
        assertTrue("no row has digits switched off", rows.any { !it.addDigits })
        assertTrue("no row uses the maximum of 5 digits", rows.any { it.digitCount == 5 })
        for (mode in listOf(Language.RANDOM, Language.MIX)) {
            assertTrue("no row covers $mode", rows.any { it.language == mode })
        }
        assertTrue("no row covers a fixed language", rows.any { it.language?.isReal == true })
        // The carry that turns 999.6 thousand into 1.0 million rather than "1000
        // thousand". Reachable only from a synthetic size, so it is easy to lose.
        assertEquals(
            "1.0 million",
            // null model on purpose: the carry lives in the size-based fallback,
            // and passing the table would look up "en" and never reach it.
            Strength.describe(null, listOf(Category.NOUN), Language.EN, WordType.NOUN,
                listOf(999_600), false, 1, Separator.HYPHEN).combinations,
        )
    }

    /**
     * The two measures MUST diverge under the random-language modes.
     *
     * If they are equal there, the model was not consulted and every figure for
     * those modes is silently the uniform fallback: plausible-looking, and wrong by
     * up to 3 bits per word. Equality under a FIXED language is the opposite, and
     * is required, because that distribution genuinely is uniform.
     */
    @Test
    fun `min-entropy and collision entropy diverge only where they should`() {
        assertNotNull("entropy model did not parse", model.lookup(Language.MIX, WordType.NOUN, 1))
        for (row in rows.filter { it.language?.isReal == true }) {
            assertEquals("fixed language must be uniform at ${row.case}", row.hmin, row.h2, 1e-9)
        }
        // MIX is uniform too, now that it draws from the pooled vocabulary rather
        // than picking a language and then a word, so it must NOT diverge either.
        for (row in rows.filter { it.language == Language.MIX }) {
            assertEquals("pooled mix must be uniform at ${row.case}", row.hmin, row.h2, 1e-9)
        }
        // RANDOM is the one genuinely non-uniform mode: one draw fixes the language
        // for the whole name and the lists differ in size. If the two measures match
        // there, the table was not read and every random figure is the fallback.
        val random = rows.filter { it.language == Language.RANDOM && !it.addDigits && it.slots >= 2 }
        assertTrue("no digit-free random rows to compare", random.isNotEmpty())
        for (row in random) {
            assertTrue(
                "random mode shows equal measures at ${row.case}; the model was not read",
                row.h2 - row.hmin > 0.1,
            )
        }
        // Pooling must actually beat every fixed language, or it is not happening.
        val mixOne = rows.first { it.language == Language.MIX && it.wordType == WordType.NOUN &&
            it.slots == 1 && !it.addDigits }
        for (row in rows.filter { it.language?.isReal == true && it.wordType == WordType.NOUN &&
                it.slots == 1 && !it.addDigits }) {
            assertTrue("pooled mix does not beat ${row.language!!.code}", mixOne.hmin > row.hmin)
        }
    }

    /**
     * Proves Kotlin's categoryPlan agrees with the web app's, using the real word
     * lists rather than a restatement of them.
     */
    @Test
    fun `category plan agrees with the web app across every language and type`() {
        // Counted the way the app counts: entries that would DISPLAY identically are
        // one word, so "male" and "måle" contribute 1, not 2. Counting raw lines
        // would disagree with what the generator can actually produce.
        fun size(lang: String, category: Category) =
            File(dataDir, "${lang}_${category.suffix}.txt").readLines()
                .filter { it.isNotBlank() }
                .map { UsernameEngine.sanitise(it.trim()) }
                .distinct().size

        var checked = 0
        for (row in rows.filter { it.language?.isReal == true && !it.case.startsWith("synthetic/") }) {
            val plan = UsernameEngine.categoryPlan(row.slots, row.wordType)
            assertEquals(
                "plan sizes differ from the web app at ${row.case}",
                row.sizes,
                plan.map { size(row.language!!.code, it) },
            )
            checked++
        }
        assertTrue("no real rows were checked", checked >= 1000)
    }

    /**
     * The two separator modes must be worth exactly what they claim.
     *
     * RANDOM is one draw for the whole name, so log2(4) however long it is. MIX is
     * one draw per gap, so log2(4) times the gaps. Neither is worth anything on a
     * one-word name, which has no gap to put a separator in. Checked against the
     * fixed-separator row for the same configuration, so this measures the
     * difference the mode makes rather than restating the arithmetic.
     */
    @Test
    fun `separator modes are worth exactly one draw and one draw per gap`() {
        val perDraw = 2.0 // log2(4)
        val byKey = rows.filter { it.language != null }
            .associateBy { Triple(it.case, it.digitCount to it.addDigits, it.separator) }
        var checked = 0
        for (row in rows.filter { it.separator == Separator.HYPHEN && it.language != null }) {
            val key = Triple(row.case, row.digitCount to row.addDigits, Separator.RANDOM)
            val random = byKey[key] ?: continue
            val mix = byKey[Triple(row.case, row.digitCount to row.addDigits, Separator.MIX)]!!
            val gaps = row.slots - 1
            assertEquals(
                "random separator at ${row.case} should add ${if (gaps > 0) perDraw else 0.0}",
                if (gaps > 0) perDraw else 0.0, random.hmin - row.hmin, 1e-9,
            )
            assertEquals(
                "mix separator at ${row.case} should add ${gaps * perDraw}",
                gaps * perDraw, mix.hmin - row.hmin, 1e-9,
            )
            checked++
        }
        assertTrue("no configurations compared", checked >= 250)
    }

    /** The strongest settings must be computed, and must actually be the strongest. */
    @Test
    fun `max entropy options really are the maximum`() {
        val best = Strength.maxEntropyOptions(model)
        assertEquals(Language.MIX, best.language)
        assertEquals(Settings.MAX_WORDS, best.wordCount)
        assertEquals(Settings.MAX_DIGITS, best.digitCount)
        assertEquals(Separator.MIX, best.separator)
        // Beat it if you can, across every option the UI offers.
        for (language in Language.entries) {
            for (type in WordType.entries) {
                for (words in Settings.MIN_WORDS..Settings.MAX_WORDS) {
                    for (digits in Settings.MIN_DIGITS..Settings.MAX_DIGITS) {
                        val plan = UsernameEngine.categoryPlan(words, type)
                        val sizes = if (language.isReal) {
                            plan.map { category ->
                                File(dataDir, "${language.code}_${category.suffix}.txt")
                                    .readLines().filter { it.isNotBlank() }
                                    .map { line -> UsernameEngine.sanitise(line.trim()) }
                                    .distinct().size
                            }
                        } else {
                            emptyList()
                        }
                        val got = Strength.describe(
                            model, plan, language, type, sizes, true, digits, Separator.MIX)
                        assertTrue(
                            "${language.code}/${type.key}/$words/$digits beats the claimed maximum " +
                                "(${got.hmin} > ${best.strength.hmin})",
                            got.hmin <= best.strength.hmin + 1e-9,
                        )
                    }
                }
            }
        }
    }
}
